"""Add Phase 4 models: PayrollCalculation, FileGeneration, UserActivity

Revision ID: 8ea715dfd8b4
Revises: 34cb4514bf11
Create Date: 2025-12-10 14:25:18.497864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea715dfd8b4'
down_revision = '34cb4514bf11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_generations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_generations_file_type'), ['file_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_generations_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_generations_user_id'), ['user_id'], unique=False)

    op.create_table('payroll_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('total_payroll', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_net_pay', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('calculation_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payroll_calculations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_calculations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_calculations_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_calculations_user_id'), ['user_id'], unique=False)

    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activities_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activities_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_activities_activity_type'))

    op.drop_table('user_activities')
    with op.batch_alter_table('payroll_calculations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_calculations_user_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_calculations_period'))
        batch_op.drop_index(batch_op.f('ix_payroll_calculations_created_at'))

    op.drop_table('payroll_calculations')
    with op.batch_alter_table('file_generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_generations_user_id'))
        batch_op.drop_index(batch_op.f('ix_file_generations_period'))
        batch_op.drop_index(batch_op.f('ix_file_generations_file_type'))
        batch_op.drop_index(batch_op.f('ix_file_generations_created_at'))

    op.drop_table('file_generations')
    # ### end Alembic commands ###
